# Generated by Django 4.0.2 on 2022-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='city_name',
            field=models.CharField(default='Nur-Sultan', max_length=30),
        ),
        migrations.AddField(
            model_name='status',
            name='city_name',
            field=models.CharField(default='Nur-Sultan', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_location',
            field=models.CharField(max_length=50),
        ),
    ]
