# Generated by Django 4.0.2 on 2022-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-author', '-title'], 'verbose_name': 'Мақала', 'verbose_name_plural': 'Мақалалар'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='describe',
            field=models.TextField(default='DataFlair Django tutorials'),
        ),
        migrations.AlterModelTable(
            name='posts',
            table='МақАла',
        ),
    ]
