# Generated by Django 4.0.2 on 2022-04-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_options_alter_posts_describe_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
