# Generated by Django 4.0.2 on 2022-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырып')),
                ('is_published', models.BooleanField(default=True, verbose_name='Шығарылым')),
                ('slug', models.BooleanField(db_index=True, max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
