# Generated by Django 4.0.2 on 2022-04-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_posts2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts2',
            name='slug',
        ),
    ]
