# Generated by Django 4.0.2 on 2022-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_posts2_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts2',
            name='slug',
            field=models.SlugField(default=True, max_length=255, verbose_name='URL'),
        ),
    ]
