# Generated by Django 4.0.2 on 2022-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_posts2_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts2',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
