# Generated by Django 4.0.2 on 2022-04-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_posts2_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
