# Generated by Django 4.0.2 on 2022-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_reguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reguser',
            name='lastlogindate',
        ),
        migrations.AddField(
            model_name='reguser',
            name='us_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
