# Generated by Django 4.0.2 on 2022-04-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_reguser_id_remove_reguser_lastlogindate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguser',
            old_name='us_id',
            new_name='user_id',
        ),
    ]
